apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: %CCLOUD_CLUSTER%
  name: %CCLOUD_CLUSTER%-dp
  namespace: confluent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: %CCLOUD_CLUSTER%
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: %CCLOUD_CLUSTER%
    spec:
      containers:
      - name: ccloudexporter
        image: dabz/ccloudexporter:latest
        envFrom:
          - secretRef:
              name: %CCLOUD_CLUSTER%-vars
        imagePullPolicy: Always
        ports:
        - containerPort: 2112
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ccloud-svc
  labels:
    app: %CCLOUD_CLUSTER%
spec:
  ports:
  - port: 2112
    protocol: TCP
  selector:
    app: %CCLOUD_CLUSTER%