apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-lag-exporter
  name: kafkalag-dp
  namespace: confluent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-lag-exporter
  template:
    metadata:
      labels:
        app: kafka-lag-exporter
    spec:
      containers:
      - name: kafka-lag-exporter
        image: lightbend/kafka-lag-exporter:0.6.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: "/opt/docker/conf"
          name: monitor-config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: "monitor-config"
        configMap:
          name: monitor-config
          items:
          - key: "application.conf"
            path: "application.conf"
          - key: "logback.xml"
            path: "logback.xml"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: kafkalag-dp
  labels:
    app: kafka-lag-exporter
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: kafka-lag-exporter
