{
 "title": "Schema Registry cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  { "title": "Schemas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Schema Registry Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count_registered_count{job=\"schema-registry\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_avro_schemas_deleted_avro_schemas_deleted{job=\"schema-registry\",env=\"$env\"}) + avg(kafka_schema_registry_json_schemas_deleted_json_schemas_deleted{job=\"schema-registry\",env=\"$env\"}) + avg(kafka_schema_registry_protobuf_schemas_deleted_protobuf_schemas_deleted{job=\"schema-registry\",env=\"$env\"}) ",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "JSON Schemas Created OverTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kafka_schema_registry_json_schemas_created_json_schemas_created{job=\"schema-registry\",env=\"$env\"})",
     "legendFormat": "JSON Schemas"
    }
   ]
  },
  {
   "title": "AVRO Schemas Created OverTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kafka_schema_registry_avro_schemas_created_avro_schemas_created{job=\"schema-registry\",env=\"$env\"})",
     "legendFormat": "AVRO Schemas"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count_registered_count{job=\"schema-registry\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Protobuf Schemas Created OverTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kafka_schema_registry_protobuf_schemas_created_protobuf_schemas_created{job=\"schema-registry\",env=\"$env\"})",
     "legendFormat": "Protobuf Schemas"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"schema-registry\",env=\"$env\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"schema-registry\",env=\"$env\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"schema-registry\",env=\"$env\",area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"schema-registry\",env=\"$env\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "schemaregistry_confluent_jetty_metrics_connections_active{job=\"schema-registry\",env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "schemaregistry_confluent_jersey_metrics_request_rate{job=\"schema-registry\",env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests latency 99p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "schemaregistry_confluent_jersey_metrics_request_latency_99{job=\"schema-registry\",env=\"$env\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}