{
 "title": "Zookeeper cluster-new",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  { "title": "Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zookeeper nodes online",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_apache_zookeeperservice_replicatedserver_id1_quorumsize{job=\"zookeeper\",env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_zookeeperservice_replicatedserver_id1_numaliveconnections{job=\"zookeeper\",env=\"$env\"}) + sum(org_apache_zookeeperservice_replicatedserver_id2_numaliveconnections{job=\"zookeeper\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(org_apache_zookeeperservice_replicatedserver_id1_outstandingrequests{job=\"zookeeper\",env=\"$env\"}) + sum(org_apache_zookeeperservice_replicatedserver_id2_outstandingrequests{job=\"zookeeper\",env=\"$env\"})",
     "legendFormat": "{{server_id}}:{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(org_apache_zookeeperservice_replicatedserver_id1_nodecount{job=\"zookeeper\",env=\"$env\"}) + avg(org_apache_zookeeperservice_replicatedserver_id2_nodecount{job=\"zookeeper\",env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_zookeeperservice_replicatedserver_id1_watchcount) + sum(org_apache_zookeeperservice_replicatedserver_id2_watchcount)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"zookeeper\",env=\"$env\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"zookeeper\",env=\"$env\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"zookeeper\",env=\"$env\",area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"zookeeper\",env=\"$env\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Latency - Minimum",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(org_apache_zookeeperservice_replicatedserver_id1_minrequestlatency{job=\"zookeeper\",env=\"$env\"} * org_apache_zookeeperservice_replicatedserver_id1_ticktime{job=\"zookeeper\",env=\"$env\"})",
     "legendFormat": "{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(org_apache_zookeeperservice_replicatedserver_id1_avgrequestlatency{job=\"zookeeper\",env=\"$env\"} * org_apache_zookeeperservice_replicatedserver_id1_ticktime{job=\"zookeeper\",env=\"$env\"})",
     "legendFormat": "{{member_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(org_apache_zookeeperservice_replicatedserver_id1_maxrequestlatency{job=\"zookeeper\",env=\"$env\"} * org_apache_zookeeperservice_replicatedserver_id1_ticktime{job=\"zookeeper\",env=\"$env\"})",
     "legendFormat": "{{member_type}} ({{instance}})"
    }
   ]
  }
 ]
}