global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 60s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 30s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
  - job_name: "ccloud_exporter"
    honor_timestamps: true
    static_configs:
      - targets:
          - "ccloud-svc:2112"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
  - job_name: "connect"
    static_configs:
      - targets:
          - "connect-0-internal:7778"
        labels:
          env: "dev"
          cluster: "cluster1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "ksqldb"
    static_configs:
      - targets:
          - "ksqldb-0-internal:7778"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "rest-proxy"
    static_configs:
      - targets:
          - "restproxy:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  # No producer for the moment in cp-demo
  #  - job_name: 'producer'
  #    static_configs:
  #      - targets:
  #          - 'producer:1234'
  #        labels:
  #          env: 'dev'

  # No consumer for the moment in cp-demo
  #  - job_name: 'consumer'
  #    static_configs:
  #      - targets:
  #          - "consumer:1234"
  #        labels:
  #          env: 'dev'

  - job_name: "kafka-lag-exporter"
    static_configs:
      - targets:
          - "kafkalag-dp:8000"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'    